server:
  port: 8050
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://admin:123456@peer1:8001/eureka,http://admin:123456@peer2:8002/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: file-upload-service
  http:
    multipart:
      max-file-size: 20MB
      max-request-size: 21MB