server:
  port: 10013
  context-path: /movie

eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://admin:123456@peer1:8001/eureka,http://admin:123456@peer2:8002/eureka
  instance:
    prefer-ip-address: true

spring:
  application:
    name: movie-service0
logging:
  level:
    lianxi.cloud.movie.feign.UserFeignClient: DEBUG
