spring:
  application:
    name: discovery-eureka-ha
security:
  basic:
    enabled: true
  user:
    name: admin
    password: 123456

---
spring:
  profiles: peer1
server:
  port: 8001
eureka:
  instance:
    hostname: peer1
  client:
    service-url:
      defaultZone: http://admin:123456@peer2:8002/eureka
  server:
    enable-self-preservation: false

---
spring:
  profiles: peer2
server:
  port: 8002
eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      defaultZone: http://admin:123456@peer1:8001/eureka
  server:
    enable-self-preservation: false